FROM node:16-alpine

# Set the working directory
WORKDIR /usr/local/api

# Add the source code to app
COPY ./ /usr/local/api/

# Install all the dependencies
RUN yarn install

# Generate the build of the application
RUN yarn run build

CMD yarn start:prod

# Expose port 4100
EXPOSE 4100
